version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

      